# Generated by Django 5.2 on 2025-05-02 17:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('mild', 'Mild'), ('moderae', 'Moderate'), ('severe', 'Severe')], max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='event',
            name='max_attendees',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='special_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='menu',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('takeout', 'Takeout'), ('dine-in', 'Dine_In')], default='dine-in', max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_email',
            field=models.EmailField(blank=True, default='guest@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_name',
            field=models.CharField(blank=True, default='Guest', max_length=100),
        ),
        migrations.AddField(
            model_name='reservation',
            name='guest_phone',
            field=models.CharField(blank=True, default='000000000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='reservation',
            name='special_request',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='itemsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='partySize',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='core.allergy'),
        ),
    ]
