# Generated by Django 5.2 on 2025-04-16 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='P'),
        ),
        migrations.RemoveField(
            model_name='itemsorder',
            name='order',
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
