# Generated by Django 5.2 on 2025-05-01 16:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('news', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='order',
            name='takeout',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='dateTime',
        ),
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='orderName',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='allergy',
            field=models.CharField(default='none', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reservation',
            name='hostName',
            field=models.CharField(default='none', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='P'),
        ),
        migrations.RemoveField(
            model_name='itemsorder',
            name='order',
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient'),
        ),
        migrations.AddField(
            model_name='itemsorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.order'),
        ),
    ]
