# Generated by Django 5.2 on 2025-04-16 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_reservation_datetime_event_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(null=True, to='core.ingredient'),
        ),
    ]
