# Generated by Django 5.2 on 2025-06-12 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_event_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
