# Generated by Django 5.2 on 2025-05-01 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_remove_reservation_datetime_event_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='allergy',
            field=models.CharField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='hostName',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('ingredients', models.ManyToManyField(blank=True, to='core.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='itemsorder',
            name='foodName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.food'),
        ),
        migrations.DeleteModel(
            name='Foods',
        ),
    ]
