# Generated by Django 5.2 on 2025-05-09 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_news_remove_order_reservation_remove_order_takeout_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='hostName',
            new_name='name',
        ),
    ]
