# Generated by Django 5.2 on 2025-04-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_menu_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='core.ingredient'),
        ),
    ]
