# Generated by Django 5.2 on 2025-04-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_menu_ingredients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='Food',
        ),
    ]
