# Generated by Django 5.2 on 2025-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_order_takeout_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='reservation',
        ),
        migrations.AddField(
            model_name='order',
            name='hostName',
            field=models.CharField(default=' ', max_length=32),
        ),
    ]
