# Generated by Django 5.2 on 2025-04-25 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_menu_food'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food',
            new_name='Menu',
        ),
    ]
