# Generated by Django 5.1.6 on 2025-04-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_news_reservation_allergy_reservation_hostname"),
        ("core", "0007_news"),
    ]

    operations = []
